/* eslint-disable perfectionist/sort-enums */
export enum ErrorCode {
  // Authentication Errors (401)
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Bad Request Errors (400)
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_FORMAT = 'INVALID_FORMAT',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_PARAMETER = 'MISSING_PARAMETER',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Forbidden Errors (403)
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Not Found Errors (404)
  NOT_FOUND = 'NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // Conflict Errors (409)
  CONFLICT = 'CONFLICT',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  DUPLICATE_KEY = 'DUPLICATE_KEY',

  // Rate Limit Errors (429)
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Database Errors (500)
  DATABASE_ERROR = 'DATABASE_ERROR',
  QUERY_FAILED = 'QUERY_FAILED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',

  // External Service Errors (500+)
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  GOOGLE_SHEETS_ERROR = 'GOOGLE_SHEETS_ERROR',
  API_ERROR = 'API_ERROR',

  // Internal Server Errors (500)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNCAUGHT_ERROR = 'UNCAUGHT_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}
