name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd playdigo-dashboard-server
            cat > .env << 'EOF'
            ${{ secrets.ENV_FILE_CONTENTS }}
            EOF
            git pull origin main
            npm install
            npm run build
            pm2 restart my-app || env-cmd -f .env pm2 start dist/src/app.js --name my-app
